image: Visual Studio 2019
configuration: Release
platform: Any CPU

install:
  - ps: $env:build_version = (Select-Xml -Path ".\Package.nuspec" -XPath "/package/metadata/version" | Select-Object -ExpandProperty Node).InnerText
  - ps: Update-AppveyorBuild -Version "$env:build_version.$env:APPVEYOR_BUILD_NUMBER"
  - cmd: git submodule --quiet update --init

dotnet_csproj:
  patch: false

before_build:
- cmd: dotnet restore --verbosity q

build:
  project: Unity.sln
  parallel: true
  verbosity: minimal

after_build:
- cmd: NuGet pack

artifacts:
- path: 'Unity.*.nupkg'
  name: 'Unity'
  
# publish NuGet package on tag build
#deploy:
#- provider: NuGet
#  api_key:
#    secure: oy2bh5r6l2tktqiulxea6rpj73yb6cgelcmhx4sl5yjd44
#  on:
#    appveyor_repo_tag: true